name: rapids-env

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudatoolkit=11.5
  - cupy
  - dask
  - dask-labextension
  - dask-ml
  - dask-sql
  - datashader
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.9
  - python-language-server
  - pyviz_comms
  - rapids=22.06
  - scikit-learn
  - scipy
  - ucx
  - ucx-py
  - wandb
  - xarray
  - xeus-python
  - xgboost
