name: pytorch-env

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudatoolkit=11.2
  - dask
  - dask-ml
  - dask-labextension
  - datashader
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r file:requirements.txt
  - pyarrow
  - python=3.8
  - python-language-server
  - pyviz_comms
  - rapids-blazing=21.06
  - scikit-learn
  - scipy
  - ucx
  - ucx-py
  - wandb
  - xarray
  - xeus-python
  - xgboost
