name: null

channels:
  - rapidsai
  - nvidia
  - blazingsql/label/cuda10.0
  - blazingsql
  - conda-forge
  - defaults

dependencies:
  - blazingsql-calcite=0.4.5 
  - blazingsql-orchestrator=0.4.5 
  - blazingsql-ral=0.4.5
  - blazingsql-python=0.4.5
  - cudatoolkit=10.0
  - jupyterlab=1.1
  - matplotlib=3.1
  - python=3.7
  - python-flatbuffers=1.11
  - rapids=0.10
