name: null

channels:
  - blazingsql
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - blazingsql=0.13
  - cudatoolkit=10.1
  - ipython-sql=0.3
  - jupyterlab=1.2
  - jupyterlab-git=0.9
  - matplotlib=3.2
  - nbdime=1.1
  - nodejs=13
  - pip=20.0
  - pip:
    - -r file:requirements.txt
  - python=3.7
  - python-flatbuffers=1.11
  - rapids=0.13
