name: null

channels:
  - blazingsql
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - blazingsql=0.14
  - cudatoolkit=10.1
  - jupyterlab=2.1
  - jupyterlab-git=0.20
  - pip=20.1
  - pip:
    - -r file:requirements.txt
  - python=3.7
  - rapids=0.14
