name: null

channels:
  - rapidsai
  - nvidia
  - blazingsql
  - conda-forge
  - defaults

dependencies:
  - blazingsql=0.11
  - datashader=0.9
  - ipython-sql=0.3
  - jupyterlab=1.2
  - jupyterlab-git=0.9
  - matplotlib=3.1
  - nodejs=13.0
  - pip=19.3
  - pip:
    - -r file:requirements.txt
  - python=3.7
  - python-flatbuffers=1.11
  - rapids=0.11
