name: null

channels:
  - rapidsai
  - nvidia
  - numba
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.0
  - cudf=0.9
  - cugraph=0.9
  - cuml=0.9
  - jupyterlab=1.0
  - matplotlib=3.1
  - python=3.7
  - py-xgboost-gpu=0.90
