name: null

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.1
  - jupyterlab=1.2
  - matplotlib=3.1
  - nodejs=13.0
  - pip=19.3
  - pip:
    - jupyterlab-nvdashboard==0.1.*
  - python=3.7
  - rapids=0.13
